apiVersion: v1
kind: Service
metadata:
 name: service-node
 labels:
  app: nodeapp
  author: siva
spec:
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
 selector:
  name: service-pod
  app: nodeapp
