apiVersion: v1
kind: Service
metadata:
 name: service-node
 labels:
  app: nodeapp
  author: siva
spec:
 type: LoadBalancer
 ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
 selector:
  name: service-pod
  app: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-node
 labels:
  app: nodeapp
  author: siva
spec:
 replicas: 2
 selector:
  matchLabels:
   app: nodeapp
 template:
  metadata:
   labels:
    app: nodeapp
  spec:
   containers:
    - name: nodejs
      image: siva9948/nodeapp:1
      ports:
       - containerPort: 3000
